# Generated by Django 4.1.3 on 2023-01-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xqc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="twtichuser",
            name="chats",
            field=models.ManyToManyField(to="xqc.chat"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="username",
            field=models.CharField(max_length=64),
        ),
    ]
